<?php

namespace App\Services\Payroll;

use App\Enums\Integration;
use App\Models\Booking;
use App\Models\BookingDay;
use App\Models\Client;
use App\Models\ClientContact;
use App\Models\Company;
use App\Models\EducationCandidate;
use App\Models\PaymentProvider;
use App\Models\User;
use App\Services\Booking\TimesheetPeriod;
use App\Services\Payroll\Contracts\PayrollTimesheetProvider;
use App\Services\Payroll\Evertime\EvertimeClient;
use App\Services\Payroll\Evertime\Requests\CreateClient;
use App\Services\Payroll\Evertime\Requests\GetConsultant;
use App\Services\Payroll\Evertime\Requests\SubmitTimesheet;
use App\Services\Payroll\Evertime\Requests\UpdateClient;
use App\Services\Payroll\Evertime\Requests\UpsertCandidate;
use App\Services\Payroll\Evertime\Requests\UpsertClientContact;
use App\Services\Payroll\Evertime\Requests\UpsertClientLocation;
use App\Services\Payroll\Evertime\Requests\UpsertConsultant;
use App\Services\Payroll\Evertime\Requests\UpsertPlacement;
use App\Services\Payroll\Exceptions\PayrollProviderException;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;

/**
 * Evertime's REST API (see Evertime_API_Documentationv0.34.pdf) uses
 * agency-supplied IDs throughout, so there's no round trip to capture an
 * Evertime-generated ID. IDs are resolved via HasProviderExternalId, which
 * prefers a manually-entered pre-existing Evertime ID over generating a new
 * deterministic one — this agency's Evertime account already holds years of
 * records created outside this app.
 *
 * This class owns the business decisions (is this client new to Evertime,
 * who the default/approving contact is, where a payroll period's cutoff
 * needs capping) and resolves every external ID; each class under
 * Evertime\Requests owns exactly one HTTP call — building its payload from
 * already-resolved values and sending it through EvertimeClient, the shared
 * transport.
 *
 * Most of those calls are a plain create-or-update keyed on whatever ID we
 * supply — the exception is /clients, whose POST is documented as an
 * entire overwrite of the client's Contacts and Locations. upsertClient()
 * only uses CreateClient for a client Evertime has never seen before; an
 * already-known client is updated via UpdateClient (PUT, client-level
 * fields only) plus the additive UpsertClientContact/UpsertClientLocation,
 * so an already-registered contact or location — ours or one this app has
 * no record of — never gets silently deleted by a routine sync.
 */
class EvertimeProvider implements PayrollTimesheetProvider
{
    private readonly EvertimeClient $client;

    public function __construct(private readonly Company $company)
    {
        $this->client = new EvertimeClient($company);
    }

    public function upsertClient(Client $client): void
    {
        // A row already existing here (whether auto-generated by us on a
        // previous sync, or manually entered) means this client already
        // exists in Evertime — checked before clientId() below, which would
        // otherwise create that row itself and make this always read false.
        $isNewClient = $client->providerExternalId(Integration::Evertime) === null;

        $contact = $this->defaultContact($client);
        $clientId = $this->clientId($client);
        $contactId = $this->contactId($contact, $client);
        $locationId = $this->locationId($client);

        if ($isNewClient) {
            // Confirmed live via a 422 ("Client Contact 'CONTACT-1' cannot
            // be deleted. It's being used by the following Placement(s)...")
            // when CreateClient's full-overwrite POST was sent for a client
            // that already had another contact registered — so it's only
            // ever used here, for a client Evertime has never seen before.
            (new CreateClient($this->client))->handle($client, $clientId, $locationId, $contactId, $contact);

            return;
        }

        // The contact/location must already exist in Evertime before
        // UpdateClient's PUT below can reference them as
        // MainContactId/DefaultLocationId — confirmed live via a 422 ("The
        // supplied Main Contact does not exist for this Client") when the
        // PUT ran first and pointed at a contact that hadn't been
        // registered yet.
        (new UpsertClientLocation($this->client))->handle($client, $clientId, $locationId);
        (new UpsertClientContact($this->client))->handle($client, $clientId, $contactId, $contact, default: true);
        (new UpdateClient($this->client))->handle($client, $clientId, $contactId, $locationId);
    }

    public function upsertPaymentProvider(PaymentProvider $paymentProvider): void
    {
        // Evertime has no standalone "create a Company" endpoint — a Company
        // (their term for a candidate's Ltd/umbrella company) is only ever
        // created as a nested object inside a Candidate POST. This just
        // makes sure the external ID exists (generating one if this is a
        // genuinely new payment provider) so upsertCandidate() can reference
        // it; the actual creation happens there.
        $this->paymentProviderId($paymentProvider);
    }

    public function upsertCandidate(Model $candidate): void
    {
        $paymentProvider = ($candidate->payment_provider_id && $candidate->paymentProvider) ? $candidate->paymentProvider : null;
        $paymentProviderId = $paymentProvider ? $this->paymentProviderId($paymentProvider) : null;

        (new UpsertCandidate($this->client))->handle($candidate, $this->candidateId($candidate), $paymentProvider, $paymentProviderId);
    }

    public function upsertConsultant(User $consultant): void
    {
        (new UpsertConsultant($this->client))->handle($consultant, $this->consultantId($consultant));
    }

    /**
     * Looks up an existing consultant by their Evertime Display Id — mainly
     * useful for verifying a manually-entered "Payroll Provider ID" actually
     * resolves to a real consultant before relying on it.
     *
     * @return array<string, mixed>|null
     */
    public function getConsultant(string $consultantId): ?array
    {
        return (new GetConsultant($this->client))->handle($consultantId);
    }

    public function upsertPlacement(Booking $booking): void
    {
        $client = $booking->client;
        $contact = $this->defaultContact($client);

        (new UpsertPlacement($this->client))->handle(
            $booking,
            $this->placementId($booking),
            $this->candidateId($booking->candidate),
            $this->clientId($client),
            $this->locationId($client),
            $this->contactId($contact, $client),
            $booking->consultant ? $this->consultantId($booking->consultant) : null,
        );
    }

    public function submitTimesheet(Booking $booking, Collection $approvedDays): void
    {
        // $approvedDays is expected to already be scoped to a single payroll
        // period by the caller (SendTimesheetToPayrollProvider groups by
        // period) — the cutoff is the period's actual end date, not just the
        // latest date among whichever days happen to be included, since not
        // every day in a period is necessarily approved yet.
        $periodEnd = TimesheetPeriod::containing($this->company, $approvedDays->min('date'))['end'];

        // A booking that ends mid-period (e.g. a 3-day booking inside a
        // weekly payroll period) registers that same earlier date as the
        // placement's EndDate in Evertime (see upsertPlacement()) — the
        // period's own, later calendar boundary would exceed it. Confirmed
        // live via a 422 ("The PeriodEndDate supplied is after the end date
        // of placement...").
        if ($booking->end_date && $booking->end_date->lt($periodEnd)) {
            $periodEnd = $booking->end_date;
        }

        $approver = $this->approverContactFor($booking->client, $approvedDays);

        // The person who actually approved these days on the client portal
        // may not be the client's default/timesheet contact already
        // registered via upsertClient() — make sure whoever it was is known
        // to Evertime before referencing them. Skip this when it IS the
        // default contact (approverContactFor() falls back to it when no
        // portal approver was recorded): UpsertClientContact always sends
        // DefaultContact: false, which would demote the default Evertime
        // already has for it — confirmed live via a 422 ("No default Client
        // Contact supplied") on the very next call once that happened.
        if ($approver && $approver->isNot($this->defaultContact($booking->client))) {
            (new UpsertClientContact($this->client))->handle(
                $booking->client,
                $this->clientId($booking->client),
                $this->contactId($approver, $booking->client),
                $approver,
                default: false,
            );
        }

        (new SubmitTimesheet($this->client))->handle(
            $booking,
            $approvedDays,
            $this->placementId($booking),
            $periodEnd->toDateString(),
            $this->contactId($approver, $booking->client),
        );
    }

    private function clientId(Client $client): string
    {
        return $client->resolveProviderExternalId(
            Integration::Evertime,
            fn (): string => "CLIENT-{$client->id}",
        );
    }

    private function candidateId(Model $candidate): string
    {
        // Candidate models outside Education/Healthcare (e.g. the generic
        // Candidate) don't carry the payroll-specific fields Evertime needs
        // (NI number, date of birth, bank details) or the
        // HasProviderExternalId trait — surfaced as a normal payroll
        // failure (recorded/logged by SendTimesheetToPayrollProvider)
        // rather than an uncaught error, since a company can have payroll
        // integration configured for a sector that isn't payroll-ready yet.
        if (! method_exists($candidate, 'resolveProviderExternalId')) {
            $candidateClass = $candidate::class;

            throw new PayrollProviderException(
                "Candidate #{$candidate->id} ({$candidateClass}) does not support payroll provider integration.",
                ["Candidate #{$candidate->id} does not support payroll provider integration."],
            );
        }

        $prefix = $candidate instanceof EducationCandidate ? 'EDU' : 'HC';

        return $candidate->resolveProviderExternalId(
            Integration::Evertime,
            fn (): string => "{$prefix}-{$candidate->id}",
        );
    }

    private function paymentProviderId(PaymentProvider $paymentProvider): string
    {
        return $paymentProvider->resolveProviderExternalId(
            Integration::Evertime,
            fn (): string => "PAYPROV-{$paymentProvider->id}",
        );
    }

    private function placementId(Booking $booking): string
    {
        return $booking->resolveProviderExternalId(
            Integration::Evertime,
            fn (): string => "BOOKING-{$booking->id}",
        );
    }

    private function consultantId(User $consultant): string
    {
        return $consultant->resolveProviderExternalId(
            Integration::Evertime,
            fn (): string => "CONSULTANT-{$consultant->id}",
        );
    }

    private function locationId(Client $client): string
    {
        return "LOCATION-{$client->id}";
    }

    /**
     * A contact-less client can't happen in practice (a client always has at
     * least a main contact before any of this matters — the same assumption
     * SendPayrollConfirmationEmail::recipientContact() already makes), so
     * $contact being null just falls back to the client-level placeholder ID
     * this used to always use, rather than adding defensive handling for a
     * state that shouldn't occur.
     */
    private function contactId(?ClientContact $contact, Client $client): string
    {
        if (! $contact) {
            return "CONTACT-{$client->id}";
        }

        return $contact->resolveProviderExternalId(
            Integration::Evertime,
            fn (): string => "CONTACT-{$contact->id}",
        );
    }

    private function defaultContact(Client $client): ?ClientContact
    {
        return $client->contacts()->where('timesheet_contact', true)->first() ?? $client->mainContact;
    }

    /**
     * Whoever most recently approved the days in this batch — falls back to
     * the client's default contact if none of them recorded an approver
     * (legacy days approved before this was tracked, or approved from the
     * CRM side rather than the client portal).
     */
    private function approverContactFor(Client $client, Collection $approvedDays): ?ClientContact
    {
        $approver = $approvedDays
            ->sortByDesc('approved_at')
            ->map(fn (BookingDay $day): ?User => $day->approvedBy)
            ->filter()
            ->first();

        return $approver?->clientContact ?? $this->defaultContact($client);
    }
}
